### ISSUE TITLE
studio.status.im has the wrong page title

### ISSUE THREAD

**Issue by Shrinks99** [status-im/status.im#107]
The [studio.status.im](https://studio.status.im/) page has the Nimbus page title resulting in the wrong page being displayed in the tab bar.

![screen shot 2018-10-28 at 7 56 18 pm](https://user-images.githubusercontent.com/5672810/47623865-85662100-daec-11e8-9214-eabd94ad0a3d.png)

**Comment by samthomson** [comment]
should this issue be moved to https://github.com/status-im/studio.status.im ?

**Comment by samthomson** [comment]
created a PR anyway
