### ISSUE TITLE
dead link on contribute page

### ISSUE THREAD

**Issue by samthomson** [status-im/status.im#108]
At the URL https://status.im/contribute/ the third block, titled 'working here', leads to a 404. I might guess it could point to https://status.im/contribute/open_positions.html as the corresponding link in the sidebar does, although that would imply duplicity so maybe it is meant to go elsewhere. Either way, a deadlink.

![image](https://user-images.githubusercontent.com/6588340/47642772-9d43b080-db91-11e8-8050-abfd126c972a.png)

**Comment by samthomson** [comment]
happy to fix if assigned to me and a target link specified :)

**Comment by andytudhope** [comment]
Cool, the link you listed above is the correct one. Please make sure to submit a PR to `develop` ❤️
