### ISSUE TITLE
Principles body text doesn't match actual principles

### ISSUE THREAD

**Issue by oskarth** [status-im/status.im#129]
It's great to see our principles on the website. However, they aren't represented accurately. Compare https://status.im/contribute/our_principles.html vs https://our.status.im/our-principles/

I don't think it is wise to abbreviate these, as quite a lot of work was put into exact formulation and getting consensus across a majority of the organization.

**Comment by andytudhope** [comment]
Will be updated on the live site once Jakub is done with his changes to the nightly pipeline and I can merge it all in one go: https://github.com/status-im/status.im/commit/dd97ec049c741974c791e215fa22c3a7379f1c8c
