### ISSUE TITLE
Add windows build to nightlies page

### ISSUE THREAD

**Issue by chadyj** [status-im/status.im#139]
Add the windows build to https://status.im/nightly/

Resurrecting this after https://github.com/status-im/status-im.github.io/pull/5 was closed on the old nightly site.

Spoke to @jakubgs and he will make this happen once @PombeirP finalizes the windows build work (any moment now!).

**Comment by PombeirP** [comment]
Windows PR is ready and approved, just waiting on testing :fireworks:

**Comment by andytudhope** [comment]
@andmironov how are we doing with implementing that popup you showed off in screenshots in the other issue?

**Comment by andmironov** [comment]
No need for the popup anymore?

**Comment by andytudhope** [comment]
Incorrectly closed, definitely still a need for the popup @andmironov

**Comment by andytudhope** [comment]
No, actually, this issue was right to close. We can track the popup work in #95 and close that once you have submitted it.
