### ISSUE TITLE
Add builds timestamp back on the main page

### ISSUE THREAD

**Issue by asemiankevich** [status-im/status.im#157]
I want to see the timestamp at https://status.im/nightly/ when builds were generated so I am not confused do i use the recent one or not. Also it could indicate that nightly was not built in timely manner.

we did have this shown on previous web page. Please bring it back

**Comment by chadyj** [comment]
ping @jakubgs 
Now it says `UPDATED: 2018/10/12 03:24:26 UTC`

**Comment by jakubgs** [comment]
Well, that's because it's hardcoded right now:
https://github.com/status-im/status.im/blob/develop/themes/navy/layout/nightly.swig#L46
Should be a simple fix.

**Comment by asemiankevich** [comment]
@jakubgs can we make this more visible too? Hardly noticed that small text (

**Comment by chadyj** [comment]
I didn't test the code but the change looks good 👍
