### ISSUE TITLE
Implement site-wide search functionality

### ISSUE THREAD

**Issue by andytudhope** [status-im/status.im#165]
This is an issue for @jakubgs.

1. Write a hexo plugin to index this site, which can be done in the build step.
2. Use an open source solution, i.e. elasticsearch, and a JS library to store and then fetch relevant search results.
3. Add necessary perms to ES cluster.
4. (Hopefully) we can implement some autocomplete functionality too.

**Comment by jakubgs** [comment]
Here is a prototype for search using the [jquery-marcopolo](https://github.com/jstayton/jquery-marcopolo) library:
https://gist.github.com/jakubgs/688d9263376f9eca98588afc214c4f7e

**Comment by jakubgs** [comment]
And with the use of the [Edge Ngram](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html) Tokenizer we now also have partial word searches on titles too:
```bash
curl -s 'https://search.status.im/dev.status.im/_search?q=extens' | jq '.hits.hits[]._source|{title,url}'
```
```json
{
  "title": "Building Blocks for Extensions",
  "url": "https://dev.status.im/extensions/building_blocks.html"
}
{
  "title": "Extensions Registry",
  "url": "https://dev.status.im/extensions/concept_registry.html"
}
{
  "title": "Extension Reference - Events",
  "url": "https://dev.status.im/extensions/reference_events.html"
}
{
  "title": "Extensions Hook",
  "url": "https://dev.status.im/extensions/concept_hook.html"
}
{
  "title": "Status Extensions",
  "url": "https://dev.status.im/developer_tools/intro_extensions.html"
}
...
```
We can also enable those for tags, categories, and excerpts later, but we shouldn't do that for the whole raw markdown of posts.

**Comment by valera-rozuvan** [comment]
The cluster seems to be down. See https://github.com/status-im/status.im/issues/643 .
