### ISSUE TITLE
move navigation popups into shared repo

### ISSUE THREAD

**Issue by samthomson** [status-im/status.im#167]
The HTML comprising the popups (community/project menu items) is duplicated across each static site. I propose sharing it as a partial in one of two ways:
- it's own standalone partial
- add it to the existing top-nav partial which is logically related

I'll look at what works best and submit a PR if assigned.

**Comment by andytudhope** [comment]
Fixed by https://github.com/status-im/status.im-partials/commit/ef5db8a4de18fe58b1e5e44c7b7f965b13850a91
