### ISSUE TITLE
tweek header nav popup z-index

### ISSUE THREAD

**Issue by samthomson** [status-im/status.im#169]
It seems the popups don't have a high enough z-index to clear all other html content. I noticed this on the live studio site: https://studio.status.im/

I'd like to take a look at this if assigned, perhaps it will lead me to tweeking the css/sass, and if the issue can best be resolved with a shared resource (and not separately on each site), I'll look at folding the css/sass into a shared module.

- [x] https://incubate.status.im/
- [x] https://studio.status.im/

![image](https://user-images.githubusercontent.com/6588340/49211727-ceaed680-f3f2-11e8-85e3-55c905bc007d.png)

**Comment by samthomson** [comment]
I have created two PRs on the respective repos to address this issue:
- https://github.com/status-im/incubate.status.im/pull/13
- https://github.com/status-im/studio.status.im/pull/9

Small CSS tweak to each did the trick.
I also considered breaking out the css into a shared module of sorts. Since there is a lot of shared Sass/CSS this wouldn't be a bad idea. Although it should be a task in itself to dissect what is shared and what is site specific (I'd guess not much). Unless the styling is set to change then it's possibly not even worth doing at the moment, wouldn't want to over complicate things for no reason. If/when that task is to be done, feel free to nudge me for it :upside_down_face:

**Comment by samthomson** [comment]
Any input on the two related PRs? Merging them will close this issue :upside_down_face:

**Comment by StatusSceptre** [comment]
@samthomson sorry for the  long response! assigning someone to review!

**Comment by StatusSceptre** [comment]
@andytudhope or @richard-ramos could you do a quick review on these PR's when you have a moment?

**Comment by samthomson** [comment]
no worries :upside_down_face:

**Comment by andytudhope** [comment]
Hey @samthomson ❤️Both Studio and Incubate have been put on ice for the time being given recent budgetary constraints, but thank you so much for these nevertheless. When/if they are revived, I will review and merge 👍

**Comment by samthomson** [comment]
Hey @andytudhope no worries, I see I submitted a PR for this on Dec 3rd, so I might guess they were still on the table back then. Hit me up with any current issues if need be :upside_down_face:
