### ISSUE TITLE
Overlapping of different components, UI is broken

### ISSUE THREAD

**Issue by nanspro** [status-im/status.im#188]
![screenshot from 2018-12-10 08-27-02](https://user-images.githubusercontent.com/24641089/49708486-d9b90080-fc55-11e8-818b-92723e95897c.png)
![screenshot from 2018-12-10 08-27-12](https://user-images.githubusercontent.com/24641089/49708492-db82c400-fc55-11e8-8f6d-aef0a404880a.png)
![screenshot from 2018-12-10 08-27-27](https://user-images.githubusercontent.com/24641089/49708493-dd4c8780-fc55-11e8-8649-9a41ad76512d.png)

**Comment by asemiankevich** [comment]
@jakubgs @mandrigin @chadyj ^ not sure who is responsible for such issues

**Comment by jakubgs** [comment]
Partials are broken:
https://ci.status.im/job/misc/job/status.im/200/consoleFull
```
[07:09:33] Starting 'generate'...
[32mINFO [39m Start processing
[32mINFO [39m Files loaded in 1.31 s
[43mWARN [49m Partial partial/shared-partials/partials/community-popup does not exist. (in partial/header.swig)
[43mWARN [49m Partial partial/shared-partials/partials/projects-popup does not exist. (in partial/header.swig)
[43mWARN [49m Partial partial/shared-partials/partials/search does not exist. (in page.swig)
[43mWARN [49m Partial partial/shared-partials/partials/search does not exist. (in page.swig)
[43mWARN [49m Partial partial/shared-partials/partials/search does not exist. (in page.swig)
[43mWARN [49m Partial partial/shared-partials/partials/search does not exist. (in page.swig)
[43mWARN [49m Partial partial/shared-partials/partials/search does not exist. (in page.swig)
[43mWARN [49m Partial partial/shared-partials/partials/search does not exist. (in page.swig)
[43mWARN [49m Partial partial/shared-partials/partials/search does not exist. (in page.swig)
...
```

**Comment by jakubgs** [comment]
Interestingly enough the build did't fail despite missing partials.

**Comment by jakubgs** [comment]
Oh, I see, partials submodule is pointing at `431b1aa` commit:
https://github.com/status-im/status.im/tree/develop/themes/navy/layout/partial
Which is pretty old:
https://github.com/status-im/status.im-partials/commit/431b1aa772738a9152fe71a3f426d4d9db81a43c
26 days old.

**Comment by jakubgs** [comment]
Oh interesting, it was my commit  from 4 days ago that touched partials:
https://github.com/status-im/status.im/commit/abd8be1174c50711f330f24e6ea06151018ce4be
Even though I didn't change anything in them.

**Comment by jakubgs** [comment]
Fixed with updating partials submodule at newest commit:
https://github.com/status-im/status.im/commit/554531aecf05960798288560d3b47a3e7d4be75a

**Comment by jakubgs** [comment]
It's annoying how easy it is to commit a submodule change without noticing. This has happened a few times already. Maybe there is a way to warn about it.

**Comment by asemiankevich** [comment]
@jakubgs testing? :)

**Comment by jakubgs** [comment]
Also, it makes no sense that hexo finished building without errors despite missing parts of theme. This needs to be changed too.

**Comment by jakubgs** [comment]
>@jakubgs testing? :)

Explain?

**Comment by asemiankevich** [comment]
i am just asking if testing can help from any point to help with 

> It's annoying how easy it is to commit a submodule change without noticing. This has happened a few times already. Maybe there is a way to warn about it.

**Comment by jakubgs** [comment]
I don't think an automated test could check for this. How would a test know if a submodule change is valid or not?

Also, it's sad that we hav eto use submodules in the first place:
https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/

They are pretty flimsy.

**Comment by jakubgs** [comment]
I see no clear way of making hexo fail when partials are missing so I've opened this:
https://github.com/hexojs/hexo/issues/3384
We'll see what they say. For now I'm closing this.

**Comment by jakubgs** [comment]
I guess one way would be to install [git-hooks](https://www.npmjs.com/package/git-hooks) and add a check when submodules are changed. Ask user for confirmation.

**Comment by asemiankevich** [comment]
@jakubgs the ui is still broken

**Comment by jakubgs** [comment]
The fact that header encroaches on nightlies links is a CSS issue, not a missing partial issue.

**Comment by mandrigin** [comment]
@jakubgs but who wrote this CSS?

**Comment by andytudhope** [comment]
My apologies for poor CSS 😜 Was never really my strong suit. Also, @jakubgs we did do a bunch of research with @samthomson on submodules vs subtrees vs npm packages and thought the submodules was likely the most robust (even if still not ideal): https://github.com/status-im/status.im/issues/106#issuecomment-436178708

**Comment by samthomson** [comment]
Splitting up repos is complicated. @jakubgs that article lists several alternatives to submodules although also lists the faults with each - thus the specific advantage of each alternate approach seems a moot point. I feel like there is no silver bullet. Although I do see the pain points of using submodules. If not implemented carefully submodules are frustrating to say the least. I wonder if it's just a case of updating workflows to be as smooth as possible, for example your CI system or readmes should have the correct commands (that pull submodules too). git-hooks and other scripts can help, yet also abstract away what's going on and thus make it easier to overlook. Are there any specific pain points we can problem solve on?
