### ISSUE TITLE
Get Desktop download links points to outdated nightly

### ISSUE THREAD

**Issue by jorisbontje** [status-im/status.im#189]
The nightly build download links on https://status.im/get_desktop/ are of 2018-10-25 

I'd suggest to not give a download link at all or point to the most recent nightly, the current outdated link is confusing.

Related to https://github.com/status-im/status.im/issues/95

**Comment by mattatgit** [comment]
Related: Mac desktop client download link on https://dev.status.im/get_desktop/ is currently broken 

https://status-im.ams3.digitaloceanspaces.com/StatusIm-181025-083129-0bc9fb-nightly.dmg
