### ISSUE TITLE
Get status website ready for desktop alpha release 

### ISSUE THREAD

**Issue by pablanopete** [status-im/status.im#195]
Scope TBD

**Comment by rachelhamlin** [comment]
This is the current desktop download screen: https://status.im/get_desktop/

TO DO

1. Add/update links to all builds

2. Add disclaimer about Alpha status. Somewhere we need to add:
`This is alpha software and may contain vulnerabilities. Please expect changes.`

**Comment by rachelhamlin** [comment]
Build links-

macOS: https://ci.status.im/job/status-react/job/combined/job/desktop-macos/4971/artifact/StatusImPackage/StatusIm-181224-165548-797a3a-release.dmg

Linux: https://ci.status.im/job/status-react/job/combined/job/desktop-linux/4958/artifact/StatusImPackage/StatusIm-181224-165548-797a3a-release.AppImage

Windows: https://ci.status.im/job/status-react/job/combined/job/desktop-windows/1443/artifact/StatusImPackage/StatusIm-181224-165548-797a3a-release.exe

**Comment by noman-land** [comment]
Hey, I'm attempting to make these updates but having some trouble navigating all the submodules in this repo on my fork. Based on the README, the idea of the develop branch is to be able to be more liberal with who can commit. Any chance I could get commit access here so I don't have to maintain my own fork?

**Comment by pablanopete** [comment]
@oskarth @naghdy can you help with adding @noman-land to this repository?
