### ISSUE TITLE
Outdated "Extend Your Chat" tutorial

### ISSUE THREAD

**Issue by speedyFixer** [status-im/status.im#198]
Hi, I'm learning how add extensions so I followed the docs and I found some problems with the "Extend Your Chat" tutorial.

"hooks/commands.dtwitter" must be changed with "hooks/chat.command.dtwitter"

I'm checking for more problems in the tutorial, I will update this issue if I found more and later I will make a PR with updated version.

**Comment by jeluard** [comment]
@speedyFixer Thanks for your PR!
