### ISSUE TITLE
Typos in build_status

### ISSUE THREAD

**Issue by speedyFixer** [status-im/status.im#209]
Hello, I found two typos in "index.md" from build_status directory.

branch: develop
commit: fc94d35

I'm going to make a PR for fix them.

**Comment by pablanopete** [comment]
Heh; the word in question is actually tongue in cheek for the famous "BUIDL" in ethereum. So this wasn't necessarily a typo but rather a ode to BUIDL.

Though the meme is probably played out at this point https://twitter.com/hashtag/buidl?lang=en

The make run commit looks like a solid catch though!  Thanks for contributing :)
