### ISSUE TITLE
local build/serve not working due to undefined elasticsearch stuff.

### ISSUE THREAD

**Issue by samthomson** [status-im/status.im#219]
![image](https://user-images.githubusercontent.com/6588340/51106057-4eff8e80-181d-11e9-9c71-a79ad7a6feb0.png)

As per the read me I `npm i` and then build (`./node_modules/.bin/gulp build`) and serve (`./node_modules/.bin/hexo serve`)

building works, but serving leads to the error in my console above, and the site not loading/rendering.

Observed on **develop**  branch

**Comment by samthomson** [comment]
Just me or can anyone else reproduce?

**Comment by andytudhope** [comment]
@jakubgs we're trying to move as much of the shared JS between sites as we can into a common repo. Would be pretty cool to have the elastic search indexing everything from all sites and allow me to find an article about Nimbus from the main Status site (for instance). wdyt? Asking too much? 😛

**Comment by samthomson** [comment]
Thanks @jakubgs :upside_down_face: 
Got it working and can close this issue.
