### ISSUE TITLE
Broken links on https://status.im/docs/FAQs.html

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/status.im#238]
The links in the "would like to contribute to the project, where would you suggest I start?" section don't seem to be working, specifically these 2:

"If you’re a DApp developer, head over to those [1] docs. If you are a mobile developer yourself and love functional languages, then build Status [2] yourself and start submitting those PRs."

Both return a 404 error for their links:
https://status.im/docs/intro_dapps.md
https://status.im/docs/build_status.md

But I'm not sure where they should point to, so creating an issue.

**Comment by jakubgs** [comment]
Outdated.
