### ISSUE TITLE
Update https://status.im/get_desktop/ and https://status.im/stable/ with links to 0.10.1 build 30 artefacts

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status.im#250]
Currently https://status.im/get_desktop/ and https://status.im/stable/  contain links to older Desktop versions.

We have tested Desktop builds from https://ci.status.im/job/status-react/job/release/job/release%252F0.10.x/30/ and they are good enough to be called new stable. We also need this fresh version because after merging https://github.com/status-im/status-react/pull/7670 on March 18 older Desktop versions will not receive 1:1 and group chat messages from users on nightly and future 0.11.0 release. So, need to start promoting this 0.10.1 version and ask users to upgrade Desktop build.

Exact new links:
Mac: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.dmg
Windows: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.exe
Linux: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.AppImage

**Comment by andytudhope** [comment]
https://github.com/status-im/status.im/commit/bf63188b8d2f30d7200b0d96fcc986bbeae26264

Build should be complete in the next minute 👍

**Comment by annadanchenko** [comment]
@andytudhope re-opening as there are no changes on https://status.im/get_desktop/ and https://status.im/stable/  there are still old links:
1. on get_desktop there are links with StatusIm-190207-165357-d58fb5-release instead of expected StatusIm-190305-152317-ff3c9d-release
2. on https://status.im/stable/ there are links to  StatusIm-190207-165357-d58fb5-release

**Comment by andytudhope** [comment]
I have updated manually for now. @jakubgs could you check why the stable stuff is not updating (is it just because it needs a specific link, not necessarily the latest?) and what's happening with the desktop links?

**Comment by jakubgs** [comment]
The `/get_desktop` page clearly takes the URLs from the `sources/_data/releases.yml` file:
https://github.com/status-im/status.im/blob/0818c818402d3f3d6b19b996fa609eb0b9c44eb7/themes/navy/layout/get_desktop.ejs#L15-L21
So that file has to have the correct URLs.

**Comment by jakubgs** [comment]
Oh, and to what @andytudhope said, the `releases.yml` file is not currently being auto updated. I've removed that before my vacation in https://github.com/status-im/status.im/commit/ab064acfc56df1a7aaccab647ff300f0c781e678 when I remove the `releases` task from the `build` and `run` tasks sequence.

**Comment by jakubgs** [comment]
I'm pretty sure this is already done. Closing.
