### ISSUE TITLE
Site Overhaul Prep

### ISSUE THREAD

**Issue by jakubgs** [status-im/status.im#268]
Here I'll be tracking progress of switching our site to the new overhauled version created by @NistorCristian at https://github.com/NistorCristian/status.

**Comment by jakubgs** [comment]
I've created the [nistor-christian](https://github.com/status-im/status.im/tree/nistor-christian) branch to test out his changes by doing:
```bash
git checkout develop
git pull
git checkout -b nistor-christian
git remote add nistor https://github.com/NistorCristian/status.git
git fetch nistor
git reset --soft nistor/master
git commit -s
git push
```

**Comment by jakubgs** [comment]
Also had to adjust `Jenkinsfile` conditional:
https://github.com/status-im/status.im/commit/09b330352cac1ab0a4ee420164dbdc027d5b057c

**Comment by jakubgs** [comment]
I can already see some issues with the repo.

For example @NistorCristian replaced the `shared-partials` git submodule with a regular folder:
https://github.com/NistorCristian/status/tree/master/themes/navy/layout/partial/shared-partials
But left the `.gitmodules` file unchanged:
https://github.com/NistorCristian/status/blob/master/.gitmodules

**Comment by jakubgs** [comment]
Same goes for `themes/navy/source/js/shared-js`:
https://github.com/NistorCristian/status/tree/master/themes/navy/source/js/shared-js

We'll have to fix this before we deploy.

**Comment by jakubgs** [comment]
And ran a manual build:
https://ci.status.im/job/misc/job/dev.status.im/689/
So now the new site is deployed at:
https://dev.status.im/
Seems to be looking good, or at least as far as I can tell it looks the same as:
https://status.hauntedthemes.com/

**Comment by NistorCristian** [comment]
Any idea if in hexo we can put a robots.txt that disallows this domain? https://dev.status.im/

**Comment by jakubgs** [comment]
For now the `nistor-christian` branch has the changes under `shared-js` and `shared-partials` just commited directly into the repo for the sake of the test, but for the real merge we'll need to split out those changes to their respective repos:

* https://github.com/status-im/status.im-partials
* https://github.com/status-im/status.im-js

**Comment by jakubgs** [comment]
>Any idea if in hexo we can put a robots.txt that disallows this domain? https://dev.status.im/

Sure we can. We'd need to add something like:
```
User-agent: *
Disallow: /
```

**Comment by jakubgs** [comment]
Although I don't know if adding that in Hexo makes sense. I think it would make more sense to add it in the deployment process in the `Jenkinsfile` since it depends on where it's being deployed. Prod shouldn't have that file.

**Comment by jakubgs** [comment]
Done: https://github.com/status-im/status.im/pull/269

**Comment by jakubgs** [comment]
Yesterday I created commits including changes from https://github.com/NistorCristian/status repo:
https://github.com/status-im/status.im/commit/371c52e4302507ac2333dba2d9a70ac3074703ac
https://github.com/status-im/status.im-partials/commit/fcf550c046afa3b7b2391c424624813d5209815b
And those were added to `develop` and deployed:
https://dev.status.im/

I also checked the changes to [universal-links-handler](https://github.com/status-im/universal-links-handler) from https://github.com/NistorCristian/get-status and created a docker image:
```
statusteam/universal-links-handler:3fab600
```
I tested it and it's ready to go:
```
docker run --rm -it -p 8001:3000 statusteam/universal-links-handler:3fab600
```
![get_status](https://user-images.githubusercontent.com/2212681/56418905-c28bbe80-6298-11e9-810e-517844ef9508.png)

**Comment by jakubgs** [comment]
Applied a [fix for the length of the contact](https://github.com/NistorCristian/get-status/commit/6a03272fc774d30ea34615767736dec4ce4d40e4) in links handler:
```
statusteam/universal-links-handler:9b181a2
```
Looks better:
![get_status_fix](https://user-images.githubusercontent.com/2212681/56419211-c3712000-6299-11e9-81a4-3d0113bfaede.png)

**Comment by bitgamma** [comment]
commit 371c52e undid my commit ab0b46d. I added a new page and modified some other of the Keycard API

**Comment by jakubgs** [comment]
@bitgamma yeah, sorry, the way this site overhaul was done was pretty bad. The repo contents were copied without git history and just modified in a different repo. Which mad back-porting the changes into our repo a bit destructive. I'll try to re-apply your change.

**Comment by jakubgs** [comment]
Fixed: https://github.com/status-im/status.im/commit/32ae04900f5bfbb032ed5a762bb83b037205c69a

**Comment by jakubgs** [comment]
Some other things to fix: https://github.com/status-im/status.im/issues/276, https://github.com/status-im/status.im/issues/277, https://github.com/status-im/status.im/issues/278

**Comment by jakubgs** [comment]
Multiple additional fixes from @NistorCristian in https://github.com/status-im/status.im/pull/280

**Comment by jakubgs** [comment]
#280 has been fixed, @annadanchenko is there anything else we need to fix?

**Comment by jakubgs** [comment]
Moar fixes: #295, #296, #297, #298, #299

**Comment by jakubgs** [comment]
Rebased `master` on `develop`, no conflicts, 33 commits in total: https://github.com/status-im/status.im/compare/376ed6c505fdc26ddc095b6b5806a61b2d75c46d...79a79bda91fee6de0ffe659c10f893625ad259f5
Also had to fix repo URL after that because it was changed in Nistors repo: 79a79bda91fee6de0ffe659c10f893625ad259f5

**Comment by jakubgs** [comment]
I've also pushed `statusteam/universal-links-handler:9b181a2` as `statusteam/universal-links-handler:deploy` which updated the container automatically though Watchtower.

**Comment by jakubgs** [comment]
Closing this as site overhaul as finished.
