### ISSUE TITLE
Incomplete documentation: Debugging dapps

### ISSUE THREAD

**Issue by RyRy79261** [status-im/status.im#271]
### Description

The documentation for debugging specifies being connected to the same wifi and having developer mode turned on however there are no other instructions on how to connect to a machine to inspect the dapp

https://status.im/developer_tools/debug.html

**Comment by jeluard** [comment]
Follow the `guide` link. It's regular chrome remote debugging.

**Comment by RyRy79261** [comment]
Hi @jeluard 

Where within my dapp or the Status app on my phone am I to insert the code outlined by the guide link? ```  import android.webkit.WebView;

  @Override
  public void onCreate() {
    super.onCreate();
	  ...
    WebView.setWebContentsDebuggingEnabled(true);
  }```

**Comment by jeluard** [comment]
It's already done bu status, you can skip this test.

I just pushed a doc update to integrate the relevant bits directly. Thanks for pointing this!
