### ISSUE TITLE
Empty anchors on redesigned dev.status.im

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status.im#276]
1. https://dev.status.im/docs/ has "Email Us" with "empty link" https://dev.status.im/docs/# While on existing https://status.im/docs/ there is no such "entry" page and no such email us link
Expected:  use support@status.im

**Comment by jakubgs** [comment]
Fixed: https://github.com/status-im/status.im/commit/1dd2065a25f24cf5e0e26616613c5af6cc9b64e9
