### ISSUE TITLE
2 pages with wrong chat name "Join #Status-educate" while it points to #status-core and capital #Status chat name

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status.im#277]
https://dev.status.im/get-involved/educators/
https://dev.status.im/get-involved/developers/

1. in bottom of the page, section Get in touch: wrong chat name "Join #Status-educate" while it points to #status-core. 
Expected: Join #status-core 

2. Join #Status is wrong because all chat names in the app are lowercase
Expected: Join #status

<img width="1331" alt="Screen Shot 2019-04-19 at 17 30 50" src="https://user-images.githubusercontent.com/6584810/56431159-262de000-62c9-11e9-84b2-56176180c6aa.png">

**Comment by jakubgs** [comment]
Fixed: https://github.com/status-im/status.im/commit/9c3c7aa4cc075c92d2174a97e719c65874521fab
