### ISSUE TITLE
On Safari browser, About: profile pictures look squeezed in Swarm sections on small screens

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status.im#279]
1. in Safari browser open https://dev.status.im/about/ 
2. move to Active Swarms section
3. decrease width of the browser page or use mobile with portrait mode and check how profile pictures are shown

Note: on Chrome with narrow window on desktop it looks fine

![53599](https://user-images.githubusercontent.com/6584810/56433961-01d70100-62d3-11e9-8e44-559f5fc58f93.jpg)

**Comment by NistorCristian** [comment]
Fixed in #280

**Comment by annadanchenko** [comment]
tested ok on dev.status.im

![52022](https://user-images.githubusercontent.com/6584810/56587312-98603680-65e1-11e9-8930-a648a196f784.jpg)
