### ISSUE TITLE
Update analytics page

### ISSUE THREAD

**Issue by kevinsimper** [status-im/status.im#288]
The analytics shows data from 2018 and some of the graphs are even static images.

I think it would be better for new people seeing it that it either gets removed or there is a message at the top that they are not updated :)

**Comment by corpetty** [comment]
agreed, @jakubgs do we need to keep this around for anything.  I think we can just remove it and rely on tweaking analytics.status.im, right?

**Comment by jakubgs** [comment]
Ask and you shall receive: https://github.com/status-im/status.im/pull/393

**Comment by kevinsimper** [comment]
@corpetty Didn't know about that url, great that there is something new 😄
@jakubgs Awesome 💯
