### ISSUE TITLE
Outdated links on dev.status.im/stable

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status.im#295]
dev.status.im/stable contains old links:

ios: https://i.diawi.com/dAyepW
android: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.apk
Mac: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.dmg
Linux: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.AppImage
Windows: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190305-152317-ff3c9d-release.exe

<img width="1204" alt="Screen Shot 2019-04-24 at 19 59 17" src="https://user-images.githubusercontent.com/6584810/56682365-b1ddad00-66cb-11e9-9c11-91a3250cf305.png">

### Expected links: 
(should be same as on the current status.im/stable with old design):
IOS: https://i.diawi.com/vkvAd9
Android: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190327-093035-e2cb0b-release.apk
Mac: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190329-122256-a142eb-release.dmg
Linux: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190329-122256-a142eb-release.AppImage
Windows: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190329-122256-a142eb-release.exe

<img width="1146" alt="Screen Shot 2019-04-24 at 20 02 34" src="https://user-images.githubusercontent.com/6584810/56682496-efdad100-66cb-11e9-9db2-b52e21fed690.png">

**Comment by NistorCristian** [comment]
Fixed in 680d63f

**Comment by annadanchenko** [comment]
verified ok on dev.status.im
