### ISSUE TITLE
Update Social Meta Data TW Card

### ISSUE THREAD

**Issue by j-zerah** [status-im/status.im#305]
Need to add an image to appear when URL is shared via Twitter.

Currently, the correct Title and Meta description show up but does not include an image. Please update with imagery pulled from homepage

<img width="616" alt="Screen Shot 2019-05-01 at 2 18 22 PM" src="https://user-images.githubusercontent.com/33129508/57034013-6e7bc500-6c1c-11e9-898f-b983dbcbe94e.png">

**Comment by jakubgs** [comment]
Is this still an issue? I think it's resolved.

**Comment by j-zerah** [comment]
resolved.
