### ISSUE TITLE
Update links on https://status.im/stable/ page with 0.12.1 mobile builds

### ISSUE THREAD

**Issue by Serhy** [status-im/status.im#315]
We need to update iOS and Android links on https://status.im/stable/ page to have 0.12.1 mobile builds

Expected links are:
**iOS:** https://i.diawi.com/CuniC9
**Android**: https://status-im.ams3.digitaloceanspaces.com/StatusIm-190506-084842-09a03e-release.apk

**Comment by jakubgs** [comment]
The links are stored in the [`source/_data/releases.yml`](https://github.com/status-im/status.im/blob/develop/source/_data/releases.yml) file:
https://github.com/status-im/status.im/blob/391615d9cf29a3ee33a1d6d0eda6795a073b8dc2/source/_data/releases.yml#L1-L2

Editing it should be trivial, you can even do it by just using the GitHub `edit` option:
https://github.com/status-im/status.im/edit/develop/source/_data/releases.yml#L1-L2
Modify the links and then change the option at the bottom:
>Create a new branch for this commit and start a pull request.

And select a branch name.

**Comment by annadanchenko** [comment]
@Serhy please add a link to ipa file too, as you can see in https://github.com/status-im/status.im/blob/develop/source/_data/releases.yml there is IOS link with ipa

**Comment by Serhy** [comment]
Diawii, IPA and APK links updated in PR https://github.com/status-im/status.im/pull/316

**Comment by annadanchenko** [comment]
@jakubgs should it be for develop or master branch?

**Comment by jakubgs** [comment]
The `develop` branch, it's correct. Because we want to first deploy the change to https://dev.status.im/ before we push it to `master` and https://status.im/.

**Comment by jakubgs** [comment]
https://dev.status.im/stable/ - Looks updated.
After I merge and verify https://github.com/status-im/status.im/pull/317 I'll push the changes to `master`.

**Comment by jakubgs** [comment]
Pushed to master: https://ci.status.im/job/misc/job/status.im/429/
