### ISSUE TITLE
Blog Not returning all posts to authors / tags

### ISSUE THREAD

**Issue by j-zerah** [status-im/status.im#323]
Looks as though there is an issue with posts associated to Authors and Tags.

When open the "Two Point Oh" (https://our.status.im/tag/two-point-oh/) tag in our.status.im - there should be 4 total posts but only 3 appear. Also when I view all posts by Bruno - not all of them return.

Seems as though there is a discrepancy of one in however it is searching/indexing posts.

@NistorCristian

**Comment by NistorCristian** [comment]
@j-zerah Fixed.
