### ISSUE TITLE
Call out Desktop Alpha state more

### ISSUE THREAD

**Issue by oskarth** [status-im/status.im#325]
https://status.im/get/
![image](https://user-images.githubusercontent.com/1552237/57751079-2ded7280-7717-11e9-9baf-f85657c09653.png)

"This is alpha software and may contain vulnerabilities.
Please expect changes."

1. Should be called out more, like in bold and bigger font.
2. Copy: possibly add that you  shouldn't import a key that has significant value in it, and that the expected users are developers

(possibly link to path to audit)

cc @j-zerah @corpetty @annadanchenko

**Comment by j-zerah** [comment]
Im ok if we increase font size to match the copy above the CTA as well as make it bold as well as italicized. Could even add and asterisk in front to call attention.

So copy would be:
"*This is alpha software and may contain vulnerabilities – do not import a key that has significant value. Code changes are regular and the expected users are developers."
