### ISSUE TITLE
[SNT Page] Acquisition Engine card overlaps with Cryptoeconomic  Research

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status.im#340]
all browsers (safari, chrome, opera), laptop
 https://status.hauntedthemes.com/snt/

scroll to Acquisition Engine card. it overlaps with  Cryptoeconomic  Research

<img width="1592" alt="Screen Shot 2019-05-20 at 18 43 04" src="https://user-images.githubusercontent.com/6584810/58038140-6b933680-7b2f-11e9-8e67-fe4f3b48e60b.png">

**Comment by NistorCristian** [comment]
This is how it's designed, isn't it?

**Comment by annadanchenko** [comment]
by design
