### ISSUE TITLE
[SNT Page] picture in Voting DApp overlaps borders of the card

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status.im#341]
all browsers (safari, chrome, opera), laptop
https://status.hauntedthemes.com/snt/

scroll to Voting DApp card. Picture overlaps top border of the card 

in Chrome(laptop):
<img width="1441" alt="Screen Shot 2019-05-20 at 18 50 07" src="https://user-images.githubusercontent.com/6584810/58038395-2a4f5680-7b30-11e9-9529-a063710738ee.png">

in Safari, mobile
![61635 (1)](https://user-images.githubusercontent.com/6584810/58038474-58349b00-7b30-11e9-8301-d8578249e879.jpg)

**Comment by NistorCristian** [comment]
The desktop is ok. That is how it's designed. Only the mobile doesn't overlap in design. Weird.
