### ISSUE TITLE
[SNT Page] change link for Voting DApp and dap.ps

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status.im#346]
https://status.hauntedthemes.com/snt/

1. Check out the Voting DApp >> https://vote.status.im/	link should be changed to https://get.status.im/browse/https://vote.status.im/
2. Browse DApps >> https://dap.ps/ link should be changed to  https://get.status.im/browse/https://dap.ps

**Comment by annadanchenko** [comment]
@j-zerah is it ok for you?

**Comment by j-zerah** [comment]
yes this is ok.

Noted here and in copy deck
