### ISSUE TITLE
[SNT Page] Mobile: Icons overlap picture inside some cards

### ISSUE THREAD

**Issue by annadanchenko** [status-im/status.im#347]
1. On mobile (Android or iOS) open https://status.hauntedthemes.com/snt/ 
2. Tap on Sticker Market or DAO & Governance card (any card with image on its top)
3. Check How GitHub and Chat icons are shown in the card

![Screenshot_20190522-151655](https://user-images.githubusercontent.com/6584810/58177722-2f81e200-7ca5-11e9-8bef-6743e34443e4.png)
![Screenshot_20190522-151833](https://user-images.githubusercontent.com/6584810/58177723-301a7880-7ca5-11e9-9138-21e071c50bab.png)

**Comment by j-zerah** [comment]
While not ideal, this is not a show stopper for me. It is a flaw in the design, but ultimately not too bad, nor impending someone from joining the associated channel.

Im ok to launch with this and come up with a design solution next week.
