### ISSUE TITLE
Old blog URL points to deprecated Medium blog

### ISSUE THREAD

**Issue by acolytec3** [status-im/status.im#416]
blog.status.im still points to the old Medium blog that hasn't been updated since 2018.  The old blog also doesn't mention that current blog updates are now at our.status.im.  Can the DNS records for blog.status.im be redirected to point to the current blog (or at least a post on the Medium site redirecting users to the current blog)?

**Comment by acolytec3** [comment]
@jakubgs Hey, just realized this has been sitting for quite a while.  Any chance this `blog.status.im` could be redirected to `our.status.im`?

**Comment by jakubgs** [comment]
Ah yes, I missed it because I was never pinged for it/assigned to it.
Done: https://github.com/status-im/infra-misc/commit/f7a5235b6ce93bbb8859beb00a90ce14a7723e1a
```
 $ curl -si https://blog.status.im/ | grep location 
location: https://our.status.im/
```
