### ISSUE TITLE
Community -> Docs -> Get Started is dead link

### ISSUE THREAD

**Issue by alexcg1** [status-im/status.im#417]
From https://our.status.im/tag/community/ , clicking the link from header menu for 'Get Started' results in "[Page not found](https://status.im/docs/contributor_guide.html)"

Link should be changed to https://status.im/technical/contributor_guide.html

**Comment by jonathanbarker** [comment]
OK thanks. I don't see where in the Ghost admin panel this change can be made.
Looks like the broken link might be within the custom theme we have. 

@ceripower Can you take a look and see if I'm missing something?

**Comment by jakubgs** [comment]
Yeah, this might require a theme fix. I'll take a look at it.

**Comment by jakubgs** [comment]
I've fixed it.
