### ISSUE TITLE
[Get Involved page] Include Sourcecred graph under the Open Source community and "top contributors" section 

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/status.im#419]
Now we have https://sourcecred.status.im/timeline/all-orgs/ showing the contributions to our top repos, it would be cool to include that somewhere on https://status.im/get-involved/ to demonstrate the contributions that do occur, and the size of the community that are involved. 

WDYT @j-zerah , @rbnpercy ?

**Comment by jakubgs** [comment]
Outdated.
