### ISSUE TITLE
[Get Status] Remove desktop links before v1 

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status.im#433]
We've paused work on desktop, and desktop is no longer compatible with the mobile app. 

As we're soon to release v1, we want to prevent users from installing these unsupported builds.

Two options:
1) Disable download links and update the copy to add that desktop is currently unavailable.
2) Remove the desktop section. Gray fill the remaining space, and/or select larger mobile assets. <-- Preferred

![image](https://user-images.githubusercontent.com/15470435/71823078-6c4bef00-3064-11ea-941e-5443903be487.png)

**Comment by j-zerah** [comment]
@NistorCristian for the "Get Status" Page - lets use one of the designs from Ivo. Lets remove Desktop as mentioned above by rachel.

Lets go with what you have here https://dev.status.im/v1/

BUT please remove everything below the fold (the SNT campaign copy):
<img width="1235" alt="Screen Shot 2020-01-14 at 6 11 21 PM" src="https://user-images.githubusercontent.com/33129508/72390768-8be4b680-36f9-11ea-8592-451c5a507bfc.png">



Finally - we need the descriptor copy to fit above the fold. Lets make the font smaller. It currently does not fit on my 13" macbook:

<img width="1279" alt="Screen Shot 2020-01-14 at 6 12 49 PM" src="https://user-images.githubusercontent.com/33129508/72390754-86876c00-36f9-11ea-96d8-7aa237376ecc.png">

**Comment by NistorCristian** [comment]
To recap a little because we have the same pages here.

So `/get/` will be exactly like `/v1/`. I'll keep them both, right?
Should I remove the SNT part only from /get/ or from both?

@j-zerah

**Comment by j-zerah** [comment]
please remove the SNT part from `/get/` only
