### ISSUE TITLE
[Docs] Nav Re-Org: Top-Level

### ISSUE THREAD

**Issue by rachelhamlin** [status-im/status.im#450]
Please edit the navigation of each section on the [docs site](https://status.im/docs/) as follows: 

### Technical Documentation

This entire section can be removed. Here's what to do with each page:

- Drop `Technical Documentation` link, but not the [page content](https://status.im/technical/). Can repurpose for `Build` section.
- Make `FAQs` a top-level nav item, at the bottom of the top-level menu
- Drop `Keycard API` link (duplicate content)
- Drop `Tutorials` link (duplicate)
- Drop `Schedule` link (duplicate
- Drop `Start contributing` link and page (useless content)
- Drop `Run Status Node` link, but not page content. Can be updated with [forthcoming instructions](https://github.com/status-im/design/issues/40#issuecomment-573138124).
- Drop `Contributor guide` link, but not page content. Will merge into `Build Status` section.

### DApp Integration Center

- Leave this section alone.

### Build Status

- Suggestions TK in another issue. Content related. 

### Tutorials

- Move this link beneath `Build Status` section.

### Keycard API

- Leave this section alone.

### Research

- Suggestions TK in another issue. Content related. 

### Security

- Suggestions TK in another issue. Content related. 

### Audits

- Drop this link/section.
- Content exists under `Security` > `Status External Audits` and can stay there.

### Guides

- Drop link and all content. Not relevant.

### Contribute to Status

- Suggestions TK in another issue. Content related.

**Comment by j-zerah** [comment]
@rachelhamlin have you seen this from B9 Labs? http://preview-5bxuue6kafu5ocp5.b9lab.com/docs/

**Comment by rachelhamlin** [comment]
No, only the DApp integration center - this is SO much better @j-zerah. Can't wait to see this implemented.
