### ISSUE TITLE
[Docs] Update contacts on contributor workflow

### ISSUE THREAD

**Issue by j-zerah** [status-im/status.im#474]
https://status.im/technical/contributor_workflow.html

**1. )Please update the following contact info:**

> Help me!
> We know that getting set up and finding a bug which is a good fit for your skills can be a challenge. We’re always looking for ways to open access, improve our processes and make it easier to participate in the open source community that is Status. If you’re having any trouble following this documentation, or hit a barrier you can’t get around, please ask in the #introduction room in chat.status.im or contact andy@status.im. We’re determined to solve hurdles for new contributors.

Update to:

> Help me!
> We know that getting set up and finding a bug which is a good fit for your skills can be a challenge. We’re always looking for ways to open access, improve our processes and make it easier to participate in the open source community that is Status. If you’re having any trouble following this documentation, or hit a barrier you can’t get around, please contact us in Status in the [#support channel](https://join.status.im/chat/public/support) or in [Discord](https://discordapp.com/invite/3Exux7Y) We’re determined to solve hurdles for new contributors.

**2. Also please update:**

> If you are that very rare breed of human known as a Nim developer, you can contribute to the status-nimbus repositories. Alternatively, ping @arnetheduck in chat.status.im and ask him what the Research team most needs help with.

to:

> If you are that very rare breed of human known as a Nim developer, you can contribute to the status-nimbus repositories. Alternatively, join the Nimbus team in the [Nimbus Discord](https://discord.gg/XRxWahP) server

**3. Also please update:**

> Ping us in the #developers channel in Status itself if you can’t build Status following that guide.

to:

> Join us in the #support channel in [Status](https://join.status.im/chat/public/support) or [Discord](https://discordapp.com/invite/3Exux7Y) if you can’t build Status following that guide.

**Comment by Irvine** [comment]
Pull request #495 created to address this, pending approval and merge.
