### ISSUE TITLE
[Features] Mobile >> Secure Messenger Section image stretched

### ISSUE THREAD

**Issue by j-zerah** [status-im/status.im#475]
https://status.im/features/

iPhoneX
Safari

first image on features page looks stretched on mobile

![IMG_9106](https://user-images.githubusercontent.com/33129508/74573185-46144b80-4f4e-11ea-8008-3332d2d2efc6.png)

**Comment by jakubgs** [comment]
@churik I believe this is fixed now after the refactor. Can you verify?
