### ISSUE TITLE
[Footer] Specs link incorrect and wrong copy

### ISSUE THREAD

**Issue by j-zerah** [status-im/status.im#476]
I believe @jakubgs wanted to add a link to the specs in the site footer under "Documentation"

The copy appears wrong and is pointing to the security page.

Please update copy from:
site.header.nav.docs.link-5

to:
Specs

and point to https://github.com/status-im/specs

@jakubgs can you make this change

**Comment by jakubgs** [comment]
But `link-5` is supposed to be `Security`:
https://github.com/status-im/status.im/blob/876e9e3f0be5c6d4674dea36e66cd01b26507da9/themes/navy/layout/partial/footer.ejs#L54

**Comment by jakubgs** [comment]
Not entirely sure what you want me to do.

**Comment by jakubgs** [comment]
Something like this?
https://github.com/status-im/status.im/pull/477
