### ISSUE TITLE
Fully close web page in Dapp browser

### ISSUE THREAD

**Issue by rstormsf** [status-im/status.im#485]
When I click X in Dapp browser, the tab is closed, but it actually still hangs in the background.
How do I know? In my Dapp, I disallow usage of multiple tabs in order to prevent overriding some values in `localStorage`. Therefore if I open https://multisender.app in Status.im, close the tab, and open it again, it tells me there are multiple tabs open. Which means Status.im doesn't really close the previous session.

My users will have to force-kill Status.im App or switch to another app. I think Status can do much better job, similar to Trustwallet or Im.Token(they do close webview sessions)

**Comment by jakubgs** [comment]
This is not the right repo for this issue. You're looking for https://github.com/status-im/status-react.
