### ISSUE TITLE
Lack of instructions for how to run automated tests

### ISSUE THREAD

**Issue by oskarth** [status-im/status.im#49]
Should be possible to do this locally IIRC.

cc @antdanchenko

**Comment by andytudhope** [comment]
@antdanchenko can I get an update here please - are you planning on adding these instructions ever? There is a `Testing` Section in the main `docs` sidebar: https://status.im/docs/

Please do so there in the next few days or close this issue.

**Comment by andytudhope** [comment]
@antdanchenko can you please update here, or can I close this?

**Comment by antdanchenko** [comment]
@andytudhope yes, I am on it, documentation always gets the lowest priority, sorry for that
