### ISSUE TITLE
Build instructions for status-react should be less brittle be using yarn instead of npm

### ISSUE THREAD

**Issue by oskarth** [status-im/status.im#51]
Actual PR/code implementation to be done by e.g. mobile team or any contributor.

Has proven to be quite gnarly.

Once this is updated, update docs.

Relevant PR: https://github.com/status-im/status-react/pull/5056

**Comment by andytudhope** [comment]
Oh, the old yarn story.... @oskarth is this ever going to happen? Feel like we've been moving over to Yarn for about a year now...

**Comment by oskarth** [comment]
We just need to find someone with otherwordly determination to make it happen. Believe!
