### ISSUE TITLE
status-go different modes how to build and test

### ISSUE THREAD

**Issue by oskarth** [status-im/status.im#52]
Right now no mention of status-go in docs.status.im. Pointer to README at a minimum, ideally specific steps for various basic configurations bootnodes/whisper/etc, as well as basic tests.

**Comment by PombeirP** [comment]
There's a ton of higher priority stuff going on, but I figure this can be done in a short amount of time, so in the spirit of Getting Things Done, I added an initial version in https://docs.status.im/docs/build_status_go.html.

**Comment by PombeirP** [comment]
@adambabik I left a TODO in there where you could plug in a page explaining how to build status-react with a custom status-go.

**Comment by andytudhope** [comment]
@PombeirP can we close this issue? I believe everything is pretty up to date now...

**Comment by PombeirP** [comment]
@andytudhope yeah, I believe so
