### ISSUE TITLE
Haskel typo in Nix blog post

### ISSUE THREAD

**Issue by sixhobbits** [status-im/status.im#527]
In [this](https://our.status.im/reproducable-builds-with-nix/) blog post on our.status.im (not sure if that's in scope for this repository), there is the following excerpt:

> Nix is a tool which uses a subset of [Haskel](https://www.haskel.com/) programming language to define the entire tree of software dependencies necessary to manage an entire Linux operating system: NixOS.

Note that

> Haskell has two "l"s
> The website is actually https://www.haskell.org/
> Neither the Nix language or Haskell is a subset of the other, though they both use some sort of lazy evaluation.

See https://github.com/NixOS/nixos-weekly/pull/124

**Comment by jakubgs** [comment]
Thanks for pointing out that typo! Fixed it.
