### ISSUE TITLE
Instructions to update public channels for PMs / others 

### ISSUE THREAD

**Issue by pablanopete** [status-im/status.im#55]
Ref here:

https://github.com/status-im/status-react/issues/5923

**Comment by andytudhope** [comment]
@yenda can we document this?

**Comment by yenda** [comment]
which section should this go into ?

**Comment by yenda** [comment]
@andytudhope which section should this go into ?

**Comment by andytudhope** [comment]
Fixed in https://github.com/status-im/status.im/commit/9fea1c50ff08053b012b419a586087687904b7c5
