### ISSUE TITLE
English grammar issue, see image

### ISSUE THREAD

**Issue by machocam** [status-im/status.im#586]
See last sentence

![Screenshot_20201014-104957](https://user-images.githubusercontent.com/7000131/95968995-7a5a4780-0e0e-11eb-829d-852fc815f7ea.jpg)

**Comment by chainvisions** [comment]
That definitely needs to be fixed. I will make a pull request very soon.

**Comment by jinhojang6** [comment]
Thanks @machocam and @chainvisions. The PR was merged
