### ISSUE TITLE
The bump for the latest beta didn't change the links on the instructions page

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/status.im#613]
Re: this commit: https://github.com/status-im/status.im/commit/12d6401e0471bb8cee47e5174898433f1342a5ec.

I'm not sure why but the instructions pages still has links for beta.4: https://status.im/user_guides/desktop_beta_install.html.

I tried clearing my cache and opening it in a browser that I've never previously used to visit that page, but I still get links for beta.4.

**Comment by jakubgs** [comment]
This was never automated.
