### ISSUE TITLE
No edit button on https://dev.status.im/ pages

### ISSUE THREAD

**Issue by jurjendevries** [status-im/status.im#629]
According the https://github.com/status-im/status.im/blob/develop/README.md "There is an edit button on each page, which will take you directly to the document you need to edit on the develop branch." . I don't see this button when browsing to https://dev.status.im/ and its subpages. I like to contribute by editing some items in the FAQ that are outdated or missing a link.

**Comment by jakubgs** [comment]
Pretty sure that line in the `README` is just outdated, and I don't really recall buttons like that ever being there, but maybe.
I think that line is just referring to the `edit` button on GitHub for the markdown files:
![image](https://user-images.githubusercontent.com/2212681/126773091-ef04c45e-c64d-421e-861a-1bc58931cc09.png)

I adjusted the wording: https://github.com/status-im/status.im/commit/ec4bb65c

https://dev.status.im/ is not intended for public use, it's only a staging page for testing changed before deploying them to prod.
