### ISSUE TITLE
Search service is broken

### ISSUE THREAD

**Issue by valera-rozuvan** [status-im/status.im#643]
In the `README.md` file of this repo - there is a link at the bottom to https://search.status.im/ . Right now there is nothing - the URL does not load. Is this expected?

**Comment by jakubgs** [comment]
You're right. It's due to our recent switch to WireGuard VPN in https://github.com/status-im/infra-hq/issues/58. I've fixed it:

![image](https://user-images.githubusercontent.com/2212681/119458481-15b88100-bd3d-11eb-8579-8f8a7bc1ebf3.png)

Thanks for reporting.

**Comment by valera-rozuvan** [comment]
@jakubgs - doesn't open for me. Tried it directly from my current location (Ukraine), and also from a jump host in Germany. Site doesn't load.

**Comment by jakubgs** [comment]
I can see it working just fine.

![image](https://user-images.githubusercontent.com/2212681/119614059-1fee8400-bdfe-11eb-9784-2c41c4d82c75.png)

No idea what your issue is.

**Comment by valera-rozuvan** [comment]
This is what I am seeing:

![image](https://user-images.githubusercontent.com/2273090/119663350-f273fb80-be3a-11eb-8e67-5c6744dff2b8.png)

**Comment by jakubgs** [comment]
Wait, are you trying to open https://search.status.im/ in the browser? Why would you do that?

**Comment by valera-rozuvan** [comment]
I see - yeah I got it wrong. Thank you :)

**Comment by jakubgs** [comment]
Just to clarify, that's just a API endpoint for ElasticSearch cluster used to provide search on the https://status.im/ website.

I've renamed it to https://search.infra.status.im/ so it looks less like a website since it appears to be confusing: https://github.com/status-im/status.im/commit/73a4139d
