### ISSUE TITLE
Integrate the new careers page from Pinpointhq

### ISSUE THREAD

**Issue by jakubgs** [status-im/status.im#656]
We are switching from GreenHouse to Pinpoint and our new jobs listings are available here: https://statusim.pinpointhq.com/

We'll need to integrate that with the jobs page on our site: https://status.im/our_team/jobs.html

**Comment by jakubgs** [comment]
I sent a query email to Pinpoint support and our CSS contact about this:

>I'm Jakub and I'm Head of Infra at Status.im. I was wondering how we could embed out careers page - https://statusim.pinpointhq.com/ - on our own jobs page.
>
>Currently we are still using GreenHouse and you can see how their jobs page is embedded currently:
>https://status.im/our_team/jobs.html
>
>But as far as I can tell this is impossible with https://statusim.pinpointhq.com/ because you are setting the `X-Frame-Options: SAMEORIGIN` header:
>
>```
>> curl -sv https://statusim.pinpointhq.com/ > /dev/null 2> >(grep X-Frame)
>< X-Frame-Options: SAMEORIGIN
>```
>
>Which prevents us from embedding it. Do you have some kind of special URL for embedding? Something like https://statusim.embed.pinpointhq.com/ that does not include that header?

**Comment by jakubgs** [comment]
And this is their response:

>Thanks for your message. Essentially we have a few ways that you can get the jobs from Pinpoint to your system. We do not allow for iframing jobs, however many of our clients use our API or RSS feed to pull through the jobs. If you see here this is the RSS feed that can post the jobs: https://statusim.pinpointhq.com/jobs.rss.
﻿I would recommend using our API though, this can be found within Pinpoint in the 'integrations' area on the left hand panel, then it's called 'Pinpoint API'. For your reference, here are our API documents that can help: https://developers.pinpointhq.com/docs

So as I predicted, they do not allow for embedding their jobs listings via iframe, which is quite pathetic.

**Comment by Stefaniach** [comment]
Just following up that we figured out we can use a custom domain instead: 
```Stef — 07/23/2021
Hey Stefania, as long as you let us know what you want the custom domain to be, we can sort it and send over a DNS record for you to input!``` 
@jakubgs @jinhojang6 any concerns with proceeding this way?

**Comment by jakubgs** [comment]
@Stefaniach yeah. If we use a domain like `jobs.status.im` then the `X-Frame-Options: SAMEORIGIN` should no longer be a blocker from embedding the page via an `iframe` tag.

**Comment by Stefaniach** [comment]
Awesomeness 💥 any time constraints I should keep in mind? 
Greenhouse will go offline on August 5th; can we just ping you here when the new site is ready to be integrated (waiting on some brand magic from Ned amongst other things).

**Comment by jakubgs** [comment]
Not really, once you get me the address I can change it pretty quickly. (though I am going out to the barber right now)

**Comment by Stefaniach** [comment]
[DNS Records d203bcdff0f6482b9520563854c15197.csv](https://github.com/status-im/status.im/files/6906556/DNS.Records.d203bcdff0f6482b9520563854c15197.csv)

Dropping it here, but let's wait til Aug 4th as I still need to make that page prettier. Okay?

**Comment by jakubgs** [comment]
@Stefaniach well, the sooner we put up these records the sooner they can setup the SSL certs. Since we are not advertising this page yet anywhere I think it's fine to do it today.

**Comment by jakubgs** [comment]
Here's the change: https://github.com/status-im/infra-misc/commit/edee7fa5

```
 > dig +short jobs.status.im                                  
db2vm556ndyw0.cloudfront.net.
52.222.230.138
52.222.230.193
52.222.230.220
52.222.230.103

 > dig +short _be4a683ac061e4bf1df200c8a70dfdff.jobs.status.im
_e7711c693dc94958ba40511b7f753f12.mvtxpqxpkb.acm-validations.aws.
```

**Comment by Stefaniach** [comment]
Thanks @jakubgs !

**Comment by jakubgs** [comment]
We added the redirects in https://github.com/status-im/status.im/commit/70921b92.

We might want to make custom page using the Pinpoint API, but for now this is fine.
