### ISSUE TITLE
Remove mobile releases schedule

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/status.im#705]
### Issue
Mobile release schedule is a page on status.im that is indexed by Google and outdated. Noticed someone referring to it on our Community Discord asking about a next release https://discord.com/channels/641364059387854899/663386050625798184/988570251786600498

https://status.im/mobile-release-schedule/#undefined

### Expected
Page is removed

**Comment by hesterbruikman** [comment]
@jakubgs I think I can manage this, but I don't have edit rights. Could you either assign your self or boost my permissions?

Original commit/places to edit: https://github.com/status-im/status.im/commit/51ca100bbbb95df9cc155506131feea96e5b72de#diff-520bf7d9167964b37e98f5b96cdf21d25524513566f9ebfc99e396303785994fR20

**Comment by jakubgs** [comment]
Sure, I've added write permissions for you, but already fixed it too: https://github.com/status-im/status.im/commit/212ed7dc
