### ISSUE TITLE
Remove downloads from desktop page

### ISSUE THREAD

**Issue by chadyj** [status-im/status.im#95]
Yay the new website looks great! Congrats everyone!

I'm giddy to see the desktop page https://status.im/get_desktop/  but the nightly releases shouldn't be distributed/promoted [yet].

The desktop team doesn't recommend people use nightlies for more than testing. It hasn't had a security review, frequently blows up, and won't be ready until the first alpha release. We even have a scary nightly disclaimer over at https://status-im.github.io/nightly/

So for now please disable the download links and say this is "coming soon".

As soon as we have the first alpha release we can re-add the links along with an alpha disclaimer.

cc @andytudhope

**Comment by andmironov** [comment]
can we keep the *Get Status Desktop* page with a single button "Get Status for Desktop". And once a user clicks that button we could show a popup with that disclaimer and show the download links in that popup? @chadyj

**Comment by chadyj** [comment]
> can we keep the _Get Status Desktop_ page with a single button "Get Status for Desktop". And once a user clicks that button we could show a popup with that disclaimer and show the download links in that popup? @chadyj

No :(

Desktop is not ready to promote until the alpha release. We still have a bunch of work to do. 

However you could make a note that we are working on the alpha release, but in the meantime nightlies are available for developers and testers.

**Comment by andmironov** [comment]
Here are the screenshots but okay :-(

<img width="1259" alt="1" src="https://user-images.githubusercontent.com/3115606/47616510-14a81000-dabe-11e8-8c1c-26f769c869f3.png">
<img width="1259" alt="2" src="https://user-images.githubusercontent.com/3115606/47616511-14a81000-dabe-11e8-9dc8-748be6d32de5.png">

**Comment by chadyj** [comment]
Pinging @corpetty for how to inform users about nightly and alpha releases

**Comment by andmironov** [comment]
Maybe we remove the "Get status for desktop" link from homepage but keep the https://status.im/get_desktop/ as on screenshots above as a replacement for nightly page? since the nightly page is public anyway

**Comment by andytudhope** [comment]
I really like the screenshots and vote for keeping the button on the home page, having the popup above with whatever warning @chadyj would like to see in it, wdyt Chad?

**Comment by chadyj** [comment]
> I really like the screenshots and vote for keeping the button on the home page, having the popup above with whatever warning @chadyj would like to see in it, wdyt Chad?

Nope get rid of it. 
The app is often broken, and will likely cause loss of data or worse. Alpha is right around the corner so lets lead with a vetted app which will still retain the disclaimer, and have an additional in-app disclaimer.

Considering the recent security, data, usability and basic functionality issues it is clear it isn't ready to promote.

**Comment by corpetty** [comment]
So we need a disclaimer of lack of security in both the download button, as well as the app itself when started.  This should be similar to that of the nightly release disclaimer, and reinforcing to not put in recovery phrases that have money or value associated with them.

**Comment by corpetty** [comment]
I like the one screenshotted above.

**Comment by andytudhope** [comment]
Ok @chadyj - the button has been removed for now. @andmironov would you mind still creating that popup as it is in the screenshot on the `get_desktop` page so that we can have it ready for the Alpha release?

**Comment by andmironov** [comment]
yep, will do!

**Comment by arnetheduck** [comment]
> the button has been removed for now

hide it behind a riddle, so only the worthy can get to it :)

**Comment by chadyj** [comment]
Desktop alpha is coming next week. I'll create a new issue adding the new designs above.
