### ISSUE TITLE
studio is a dead link - on the homepage

### ISSUE THREAD

**Issue by samthomson** [status-im/status.im#98]
Clicking the 'studio' panel doesn't do anything. Unlike embark and nimbus sections for example.
It should be a link to https://studio.status.im/

![image](https://user-images.githubusercontent.com/6588340/47602906-b3703600-da04-11e8-85fe-a7d4e57dc1fb.png)

**Comment by Shrinks99** [comment]
This is working as of now (tested on Chrome 70).

**Comment by samthomson** [comment]
Seems somebody else got to it in between my creating the issue and now: https://github.com/status-im/status.im/commit/0d559bc9dfec9fc0ed6fb1a399ba2218f29e835b

We can close this issue now.
